import { useEffect, useMemo, useRef, useState } from 'react'
import { ArrowRight, Clock3, Droplets, ExternalLink, FileSearch, Fuel, Gauge, Info, RefreshCw, Search, ShieldCheck, Thermometer, Wind, X, Zap } from 'lucide-react'
import { TwinSnapshot } from './TwinSnapshot'

const API = import.meta.env.VITE_API_URL || 'http://127.0.0.1:8000'
type Props = { token: string; station: { id: string; code: string; name: string; location?: string }; username: string; onNavigate: (target: 'OPERATIONS' | 'RECONCILIATION' | 'DIGITAL_TWIN' | 'SCENARIO_LAB', operationId?: string) => void; demoStep: number | null; onDemoToggle: () => void; onDemoNext: () => void }
type Snapshot = { station:any; role:string; revision:number; state:any[]; weather:any; operations:any[]; active_operations:any[]; scenarios:any[]; reconciliations:any[]; observations:any[]; sync:any; sync_events:any[]; conflicts:any[]; attention:any[]; audit:any[]; generated_at:string }
const date = (value?:string|null) => value ? new Date(value).toLocaleString() : 'Not recorded'
const val = (v:any) => v === null || v === undefined || v === '' ? '—' : String(v)
const formatStateValue = (value:any) => {
  if (typeof value === 'number' && Number.isFinite(value)) return new Intl.NumberFormat('en-IN', { maximumFractionDigits: 2 }).format(value)
  if (typeof value === 'string' && value.trim() && Number.isFinite(Number(value))) return new Intl.NumberFormat('en-IN', { maximumFractionDigits: 2 }).format(Number(value))
  return val(value)
}
const metricText = (item:any) => item ? `${formatStateValue(item.value)}${item.unit ? ` ${item.unit}` : ''}` : 'Unavailable'

export function CommandCenter({ token, station, username, onNavigate, demoStep, onDemoToggle, onDemoNext }: Props) {
  const [data,setData]=useState<Snapshot|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
  const [weatherStatus,setWeatherStatus]=useState('CHECKING'),[weatherMessage,setWeatherMessage]=useState(''),[weatherBusy,setWeatherBusy]=useState(false)
  const weatherRefreshStarted=useRef<string|null>(null)
  const [drawer,setDrawer]=useState<any|null>(null),[query,setQuery]=useState(''),[attentionExpanded,setAttentionExpanded]=useState(false)
  const [demoPanel,setDemoPanel]=useState(false),[demoState,setDemoState]=useState<any|null>(null),[demoBusy,setDemoBusy]=useState(false),[demoError,setDemoError]=useState('')
  const [gateway,setGateway]=useState<any|null>(null),[gatewayBusy,setGatewayBusy]=useState(false)
  const isDemoAdmin=username==='admin_hq'&&station.id==='maitri'
  async function load(){setBusy(true);setError('');try{const r=await fetch(`${API}/api/hq/command-center`,{headers:{Authorization:`Bearer ${token}`}}),d=await r.json();if(!r.ok)throw new Error(d.detail||'Command Center data unavailable');setData(d);if(d.weather)setWeatherStatus(old=>old==='CHECKING'||old==='UNAVAILABLE'?'AVAILABLE':old)}catch(e){setError(e instanceof Error?e.message:'Command Center data unavailable')}finally{setBusy(false)}}
  async function refreshOfficialWeather(force=false){setWeatherBusy(true);setWeatherMessage('');try{const r=await fetch(`${API}/api/weather/official/${station.id}/refresh${force?'?force=true':''}`,{method:'POST',headers:{Authorization:`Bearer ${token}`}}),d=await r.json();if(!r.ok)throw new Error(d.detail||'NCPOR refresh failed');setWeatherStatus(d.status||'UNAVAILABLE');setWeatherMessage(d.message||'');await load();if(d.observation)setData(old=>old?{...old,weather:d.observation}:old)}catch(e){setWeatherMessage(e instanceof Error?e.message:'NCPOR observation refresh failed');setWeatherStatus(old=>old==='AVAILABLE'||old==='LAST_NCPOR_OBSERVATION'?old:'UNAVAILABLE')}finally{setWeatherBusy(false)}}
  useEffect(()=>{void load();if(weatherRefreshStarted.current!==station.id){weatherRefreshStarted.current=station.id;void refreshOfficialWeather()}},[token,station.id])
  async function loadDemoStatus(){setDemoError('');try{const r=await fetch(`${API}/api/demo/status`,{headers:{Authorization:`Bearer ${token}`}}),d=await r.json();if(!r.ok)throw new Error(d.detail||'Demo status unavailable');setDemoState(d)}catch(e){setDemoError(e instanceof Error?e.message:'Demo status unavailable')}}
  async function loadGateway(){try{const r=await fetch(`${API}/api/gateway/status`,{headers:{Authorization:`Bearer ${token}`}}),d=await r.json();if(!r.ok)throw new Error(d.detail||'Gateway status unavailable');setGateway(d)}catch(e){setGateway({status:'UNAVAILABLE',error:e instanceof Error?e.message:'Gateway status unavailable'})}}
  async function setGatewayState(status:'CONNECTED'|'DEGRADED'|'OFFLINE'){setGatewayBusy(true);setDemoError('');try{const r=await fetch(`${API}/api/gateway/control`,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify({status})}),d=await r.json();if(!r.ok)throw new Error(d.detail||'Transport control unavailable');setGateway(d);await loadGateway()}catch(e){setDemoError(e instanceof Error?e.message:'Could not change sync transport')}finally{setGatewayBusy(false)}}
  async function demoAction(action:'seed'|'reset'){const prompt=action==='seed'?'Seed the deterministic Maitri demonstration records?':'Reset only records in the deterministic demo namespace? Persisted user records and weather history will be preserved.';if(!window.confirm(prompt))return;setDemoBusy(true);setDemoError('');try{const r=await fetch(`${API}/api/demo/${action}`,{method:'POST',headers:{Authorization:`Bearer ${token}`}}),d=await r.json();if(!r.ok)throw new Error(d.detail||`Demo ${action} failed`);setDemoState(d);await load()}catch(e){setDemoError(e instanceof Error?e.message:`Demo ${action} failed`)}finally{setDemoBusy(false)}}
  const currentState=useMemo(()=>Object.fromEntries((data?.state||[]).map(x=>[x.field,x])),[data])
  const searchResults=useMemo(()=>{const term=query.trim().toLowerCase();if(!term||!data)return[];return[
    ...data.operations.filter(x=>`${x.id} ${x.title} ${x.operation_type}`.toLowerCase().includes(term)).map(x=>({kind:'REMOTE OPERATION',id:x.id,title:x.title,record:x})),
    ...data.scenarios.filter(x=>`${x.id} ${x.name}`.toLowerCase().includes(term)).map(x=>({kind:'SCENARIO',id:x.id,title:x.name,record:x})),
    ...data.observations.filter(x=>`${x.id} ${x.metric} ${x.value}`.toLowerCase().includes(term)).map(x=>({kind:'STATION OBSERVATION',id:x.id,title:`${x.metric}: ${x.value} ${x.unit}`,record:x})),
    ...data.operations.filter(x=>x.latest_report&&`${x.latest_report.id} ${x.title}`.toLowerCase().includes(term)).map(x=>({kind:'STATION REPORT',id:x.latest_report.id,title:x.title,record:x})),
    ...data.sync_events.filter(x=>`${x.event_id} ${x.operation_id}`.toLowerCase().includes(term)).map(x=>({kind:'SYNC EVENT',id:x.event_id,title:x.operation_id,record:x})),
    ...data.reconciliations.filter(x=>`${x.id} ${x.operation_id} ${x.operation_title}`.toLowerCase().includes(term)).map(x=>({kind:'RECONCILIATION',id:x.id,title:x.operation_title||x.operation_id,record:x})),
    ...(`${data.station.name} ${data.station.code} ${data.station.id}`.toLowerCase().includes(term)?[{kind:'STATION',id:data.station.id,title:data.station.name,record:data.station}]:[]),
  ].slice(0,12)},[query,data])
  const openOperation=(id:string)=>onNavigate('OPERATIONS',id)
  const showProvenance=(title:string,value:any,meta:any)=>setDrawer({mode:'PROVENANCE',title,value,meta})
  const openAudit=async (event:any)=>{if(event.record_id){try{const r=await fetch(`${API}/api/operations/${event.record_id}`,{headers:{Authorization:`Bearer ${token}`}});if(r.ok){const record=await r.json();setDrawer({mode:'AUDIT',record});return}}catch{}}
    setDrawer({mode:'AUDIT',record:{id:event.record_id||'NOT AVAILABLE',record_type:event.event_type,station_id:station.id,created_by:event.actor_id,created_by_role:event.actor_role,created_at:event.timestamp,revision:event.revision,source:event.source,timeline:[event]}})}
  const stateValue=(field:string)=>currentState[field]
  const stateSource=(item:any)=>showProvenance(item?.field||'Operational state',`${val(item?.value)} ${item?.unit||''}`.trim(),{source:item?.source_type,source_type:item?.source_type,observation_time:item?.observed_at,station:station.name,revision:item?.revision,model_version:item?.model_version})
  const weather=data?.weather
  const weatherRows=weather?[['Temperature',weather.temperature_c,'°C'],['Pressure',weather.pressure_hpa,'hPa'],['Humidity',weather.relative_humidity_pct,'%'],['Wind speed',weather.wind_speed,weather.wind_speed_unit||'m/s'],['Wind direction',weather.wind_direction_deg,'°']]:[]
  const reviewCounts={pending:data?.reconciliations.filter(x=>['NOT_REVIEWED','REOPENED'].includes(x.status)).length||0,reviewed:data?.reconciliations.filter(x=>x.status==='REVIEWED').length||0,reopened:data?.reconciliations.filter(x=>x.status==='REOPENED').length||0}
  const demoLabels=['Station state','Digital twin','Scenario','Request','Station response','Sync','Reconciliation','Audit']
  const statusMetrics=[['POWER','power_available',Zap],['THERMAL STATE','heat_indoor',Thermometer],['FUEL','fuel_reserve',Fuel],['WATER','water_reserve',Droplets],['CRITICAL LOAD','critical_load',Gauge]] as const
  const activity=(data?.audit||[]).slice(0,6)
  const stateSources=[...new Set((data?.state||[]).map((item:any)=>item.source_type).filter(Boolean))]

  return <main className="cc-shell">
    <header className="cc-header"><div className="cc-page-title"><span className="cc-kicker">HQ OPERATIONS · {station.code}</span><h1>COMMAND CENTER</h1></div><div className="cc-session"><span><small>REVISION</small><b>#{data?.revision??'—'}</b></span><span><small>SYNC</small><b className={data?.sync.state==='SYNCED'?'cc-good':data?.sync.state==='OFFLINE'?'cc-neutral':'cc-warn'}>{data?.sync.state||'LOADING'}</b></span><span><small>PENDING · CONFLICTS</small><b>{data?.sync.pending_count??'—'} · {data?.sync.conflict_count??'—'}</b></span><span className="cc-clock"><Clock3 size={13}/>{new Date(data?.generated_at||Date.now()).toLocaleString()}</span><button className="cc-icon" onClick={()=>void load()} aria-label="Refresh Command Center"><RefreshCw size={16}/></button></div></header>
    <nav className="cc-actions"><button className="cc-action-primary" onClick={()=>onNavigate('OPERATIONS')}>OPEN REMOTE OPERATIONS <ArrowRight size={14}/></button><button onClick={()=>onNavigate('SCENARIO_LAB')}>RUN SCENARIO</button><button onClick={()=>onNavigate('RECONCILIATION')}>REVIEW OUTCOME</button><button onClick={onDemoToggle}>{demoStep===null?'DEMO GUIDE':'EXIT DEMO GUIDE'}</button>{isDemoAdmin&&<button onClick={()=>{setDemoPanel(!demoPanel);if(!demoPanel){void loadDemoStatus();void loadGateway()}}}>DEMO CONTROL</button>}</nav>
    {isDemoAdmin&&demoPanel&&<section className="cc-demo-control"><div><span className="cc-kicker">DETERMINISTIC DEMO DATA · SEPARATE FROM PERSISTED USER DATA</span><b>{demoState?.status||'CHECKING'} · {demoState?.demo_run_id||'DEMO-PRATIBIMB-001'}</b><small>Weather observations and historical datasets are independent and preserved.</small></div><button disabled={demoBusy||demoState?.status==='SEEDED'} onClick={()=>void demoAction('seed')}>{demoBusy?'WORKING…':'SEED DEMO'}</button><button disabled={demoBusy||demoState?.status!=='SEEDED'} onClick={()=>void demoAction('reset')}>{demoBusy?'WORKING…':'RESET DEMO'}</button>{demoError&&<p role="alert">{demoError}</p>}</section>}
    {error&&<div className="cc-error" role="alert">{error}<button onClick={()=>void load()}>Retry</button></div>}
    {demoStep!==null&&<section className="cc-demo"><div><b>DEMO MODE · GUIDED WORKFLOW</b><p>This guide navigates persisted records. It does not alter operation status or create records.</p></div><ol>{demoLabels.map((label,i)=><li key={label} className={i===demoStep?'current':i<demoStep?'done':''}><span>{String(i+1).padStart(2,'0')}</span>{label}</li>)}</ol><button onClick={onDemoNext}>NEXT · {demoLabels[(demoStep+1)%demoLabels.length]} <ArrowRight size={14}/></button><small>Reset removes records in the demo namespace and preserves weather and user data.</small></section>}
    {isDemoAdmin&&demoPanel&&<section className="cc-panel cc-transport-panel"><div className="cc-panel-head"><div><span className="cc-kicker">INDEPENDENT HQ ↔ STATION EDGE HTTP GATEWAY</span><h2>SYNC TRANSPORT</h2></div><button onClick={()=>void loadGateway()} aria-label="Refresh transport status"><RefreshCw size={14}/></button></div><div className="cc-transport-state"><b className={`transport-${String(gateway?.status||'unknown').toLowerCase()}`}>{gateway?.status||'CHECKING'}</b><span>HQ queued requests · {gateway?.queued_hq_operations??'—'}</span><span>Station events received · {gateway?.received_station_events??'—'}</span></div><div className="cc-transport-actions"><button disabled={gatewayBusy} onClick={()=>void setGatewayState('OFFLINE')}>STOP LINK</button><button disabled={gatewayBusy} onClick={()=>void setGatewayState('DEGRADED')}>DEGRADED</button><button disabled={gatewayBusy} onClick={()=>void setGatewayState('CONNECTED')}>RESTORE LINK</button></div><small>When OFFLINE, HQ's sync gateway rejects transport calls. Station staff use OPEN INDEPENDENT EDGE in the Station Workspace; local work and the edge SQLite outbox continue independently. These controls require the demo launcher.</small>{demoError&&<p role="alert">{demoError}</p>}</section>}
    <section className="cc-station-hero"><svg className="cc-antarctic-visual" viewBox="0 0 360 250" aria-hidden="true"><circle cx="180" cy="125" r="108"/><circle cx="180" cy="125" r="82"/><path className="cc-continent" d="M67 130 78 103 99 90 115 69 137 67 149 49 172 59 185 46 204 64 225 58 237 78 260 85 270 109 289 122 273 143 263 166 244 174 232 196 211 190 198 211 179 196 158 207 140 191 120 194 107 173 86 168 80 149 65 142Z"/><path className="cc-polar-grid" d="m139 190-8 19 7 18 12-13 4-21M104 116h152M95 137h170M112 159h135M136 86h89M180 47v164M148 55l-22 137M211 57l24 132"/></svg><div className="cc-station-identity"><span className="cc-kicker">ANTARCTIC OPERATIONS CENTER</span><h2>{data?.station?.name?.replace(' Station','').toUpperCase()||station.code}</h2><p>{data?.station?.location||station.location||'ANTARCTICA'}</p><div className="cc-tags"><button onClick={()=>stateSource(data?.state?.[0])}><small>OPERATIONAL STATE</small>{data?.state?.length?'RECORDED':'NO RECORDED STATE'} · {stateSources.join(' · ')||'NO SOURCE RECORDED'} <Info size={13}/></button><button onClick={()=>weather?showProvenance('NCPOR Environmental Observation',weather,{source:weather.source,source_type:weather.source_type,observation_time:weather.observation_time,fetched_at:weather.fetched_at,station:station.name,quality:weather.quality}):showProvenance('Environmental observation','Unavailable',{source:'NCPOR',source_type:'NCPOR_OFFICIAL_OBSERVATION'})}><small>ENVIRONMENT</small>{weather?'NCPOR OFFICIAL OBSERVATION':'UNAVAILABLE'} <Info size={13}/></button></div></div><aside><small>LAST STATE UPDATE</small><b>{date(data?.state?.map(x=>x.observed_at).filter(Boolean).sort().at(-1))}</b><small>REVISION</small><b>#{data?.revision??'—'}</b><small>SYNC · PENDING · CONFLICTS</small><b>{data?.sync.state||'—'} · {data?.sync.pending_count??'—'} · {data?.sync.conflict_count??'—'}</b></aside></section>
    <section className="cc-status-strip" aria-label="Station operational state">{statusMetrics.map(([label,field,Icon])=>{const item=stateValue(field);return <button key={field} onClick={()=>stateSource(item)}><small><Icon size={13} aria-hidden="true"/>{label}</small><b>{metricText(item)}</b><span>{item?.source_type||'NO RECORDED STATE'}</span></button>})}</section>
    <div className="cc-primary-grid"><TwinSnapshot large state={data?.state||[]} revision={data?.revision} onViewModel={()=>onNavigate('DIGITAL_TWIN')} onSource={(field,value,metadata)=>showProvenance(field,value,{...metadata,station:station.name,scenario:null,operation:null})}/><div className="cc-priority-column"><section className="cc-panel cc-attention"><div className="cc-panel-head"><div><span className="cc-kicker">OPERATIONAL PRIORITY</span><h2>ATTENTION REQUIRED</h2></div><b>{data?.attention.length??'—'}</b></div>{data?.attention.length?data.attention.slice(0,attentionExpanded?data.attention.length:1).map((item,i)=><article key={`${item.kind}-${item.operation_id||item.conflict_id||i}`}><span className="cc-attention-mark">{item.priority||'P2'}</span><div><b>{item.label}</b><small>{item.title||item.operation_id||'Environment / synchronization'} {item.operation_id?`· ${item.operation_id}`:''}</small></div><button onClick={()=>item.kind==='RECONCILIATION_REQUIRED'||item.kind==='HQ_REVIEW_PENDING'?onNavigate('RECONCILIATION'):item.operation_id?openOperation(item.operation_id):void load()}>{item.kind==='RECONCILIATION_REQUIRED'||item.kind==='HQ_REVIEW_PENDING'?'REVIEW':'OPEN'} <ArrowRight size={13}/></button></article>):<p className="cc-healthy">NO ACTIVE ATTENTION ITEMS <span>Nothing currently requires HQ action.</span></p>}{(data?.attention.length||0)>1&&<button className="cc-more-link" onClick={()=>setAttentionExpanded(!attentionExpanded)}>{attentionExpanded?'SHOW FEWER':'SHOW ALL'} {data!.attention.length} ATTENTION ITEMS <ArrowRight size={12}/></button>}</section>
      <section className="cc-panel cc-operations"><div className="cc-panel-head"><div><span className="cc-kicker">HUMAN-LED WORK · {data?.active_operations.length??'—'} ACTIVE</span><h2>REMOTE OPERATIONS</h2></div><button onClick={()=>onNavigate('OPERATIONS')}>OPEN REGISTER <ExternalLink size={13}/></button></div>{data?.active_operations.length?data.active_operations.slice(0,1).map(op=>{const latest=op.timeline?.at(-1);return <button className="cc-operation-row" key={op.id} onClick={()=>openOperation(op.id)}><span className="cc-op-priority">{op.priority}</span><span className="cc-op-copy"><b>{op.title}</b><small>{op.operation_type.replaceAll('_',' ')} · {op.id}</small><small>{latest?.event_type?.replaceAll('_',' ')||'Lifecycle event unavailable'} · {latest?.actor_id||'Actor unavailable'}</small></span><span className="cc-op-status">{op.status.replaceAll('_',' ')}</span><ArrowRight size={14}/></button>}):<p className="cc-empty compact">NO ACTIVE OPERATIONS <span>Create and queue a request in Remote Operations.</span></p>}{(data?.active_operations.length||0)>1&&<button className="cc-more-link" onClick={()=>onNavigate('OPERATIONS')}>VIEW ALL {data!.active_operations.length} ACTIVE OPERATIONS <ArrowRight size={12}/></button>}</section>
      <section className="cc-panel cc-outcome"><div className="cc-panel-head"><div><span className="cc-kicker">EVIDENCE REVIEW</span><h2>OUTCOME REVIEW</h2></div><ShieldCheck size={18}/></div><div className="cc-counts"><div><b>{reviewCounts.pending}</b><span>AWAITING HQ REVIEW</span></div><div><b>{reviewCounts.reviewed}</b><span>REVIEWED</span></div><div><b>{reviewCounts.reopened}</b><span>REOPENED</span></div></div><button className="cc-review-link" onClick={()=>onNavigate('RECONCILIATION')}>OPEN RECONCILIATION <ArrowRight size={14}/></button></section></div></div>
    <div className="cc-context-grid"><section className="cc-panel cc-environment" data-weather-status={weatherStatus} data-weather-refreshing={weatherBusy}><div className="cc-panel-head"><div><span className="cc-kicker">ATMOSPHERIC OBSERVATION · SEPARATE DATA DOMAIN</span><h2>ENVIRONMENT</h2></div><button type="button" onClick={()=>void refreshOfficialWeather(true)} disabled={weatherBusy} aria-label="Refresh NCPOR official observation" title="Fetch the latest public NCPOR weather observation"><RefreshCw size={14}/>{weatherBusy?'FETCHING…':'REFRESH NCPOR'}</button></div>{weather?<><div className="cc-weather-grid">{weatherRows.map(([label,value,unit])=><button key={String(label)} onClick={()=>showProvenance(String(label),`${val(value)} ${unit}`,{source:weather.source,source_type:weather.source_type,observation_time:weather.observation_time,fetched_at:weather.fetched_at,station:station.name,revision:null,model_version:null,scenario:null,operation:null,quality:weather.quality})}><b>{val(value)} <small>{unit}</small></b><span>{label}</span><Info size={12}/></button>)}</div><footer><b>{weatherStatus==='LAST_NCPOR_OBSERVATION'?'LAST NCPOR OBSERVATION':'NCPOR OFFICIAL OBSERVATION'}</b><span>Observed {date(weather.observation_time)} · fetched {date(weather.fetched_at)} · {weather.quality||'QUALITY UNKNOWN'}</span></footer></>:<div className="cc-unavailable">No stored NCPOR official observation is available for this station. <span>{weatherStatus} · not a system error</span></div>}{weatherMessage&&<p className="cc-weather-message" role="status">{weatherMessage}</p>}</section>
      <section className="cc-panel cc-scenarios"><div className="cc-panel-head"><div><span className="cc-kicker">SCENARIO LAB · RECENT MODEL RUNS</span><h2>SCENARIO ACTIVITY</h2></div><button onClick={()=>setDrawer({mode:'SCENARIOS',records:data?.scenarios||[]})}>ALL RECORDS</button></div>{data?.scenarios.length?data.scenarios.slice(0,3).map(s=><button className="cc-scenario" key={s.id} onClick={()=>setDrawer({mode:'SCENARIO',record:s})}><span><b>{s.name}</b><small>{s.id} · BASE REV #{s.base_revision}</small><small>{s.result?.constraints?.map((x:any)=>`${String(x.code||x.name||'CONSTRAINT').replaceAll('_',' ')}: ${x.status||'RECORDED'}`).join(' · ')||'No constraint result recorded'}</small></span><span><b>{s.model_version}</b><small>{date(s.created_at)}</small></span><ArrowRight size={15}/></button>):<div className="cc-empty compact">NO SCENARIOS RUN <span>Run a scenario to evaluate projected station constraints.</span><button onClick={()=>onNavigate('SCENARIO_LAB')}>RUN SCENARIO <ArrowRight size={13}/></button></div>}</section></div>
    <section className="cc-panel cc-timeline"><div className="cc-panel-head"><div><span className="cc-kicker">PERSISTED OPERATIONAL EVENTS</span><h2>RECENT ACTIVITY</h2></div><button onClick={()=>setDrawer({mode:'AUDIT_LIST',records:data?.audit||[]})}>VIEW AUDIT <ArrowRight size={13}/></button></div>{activity.length?<ol>{activity.map((event:any,i:number)=><li key={`${event.record_id}-${event.timestamp}-${i}`}><time>{new Date(event.timestamp).toLocaleTimeString([], {hour:'2-digit',minute:'2-digit'})}</time><span><b>{event.event_type.replaceAll('_',' ')}</b><small>{event.actor_id} · {event.actor_role}</small></span><small>REV {event.revision} · {event.source}</small></li>)}</ol>:<p className="cc-empty compact">No persisted activity is available for this station yet.</p>}</section>
    <div className="cc-evidence-grid"><section className="cc-panel cc-search"><div className="cc-panel-head"><div><span className="cc-kicker">TRACEABILITY</span><h2>RECORD SEARCH</h2></div><Search size={18}/></div><label><Search size={15}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Operation, scenario, observation or reconciliation ID"/></label>{query&&<div className="cc-search-results">{searchResults.map(x=><button key={`${x.kind}-${x.id}`} onClick={()=>x.kind==='REMOTE OPERATION'||x.kind==='STATION REPORT'?openOperation(x.record.id):setDrawer({mode:x.kind,record:x.record})}><small>{x.kind} · {x.id}</small><b>{x.title}</b><ArrowRight size={13}/></button>)}{!searchResults.length&&<p>No matching records in this station snapshot.</p>}</div>}</section>
      <section className="cc-panel cc-chain"><div className="cc-panel-head"><div><span className="cc-kicker">LATEST LINKED OPERATION</span><h2>PROVENANCE CHAIN</h2></div><FileSearch size={18}/></div>{(()=>{const op=data?.operations.find(x=>x.scenario_id)||data?.operations[0],scenario=op&&data?.scenarios.find(x=>x.id===op.scenario_id),ob=op&&data?.observations.find(x=>x.operation_id===op.id),rec=op&&data?.reconciliations.find(x=>x.operation_id===op.id),sync=op&&data?.sync_events.find(x=>x.operation_id===op.id),stationEvent=op?.timeline?.find((x:any)=>x.event_type==='STATION_OBSERVATION_RECORDED'),resultExists=scenario&&scenario.result;const nodes=[['SCENARIO',scenario?.id,scenario?()=>setDrawer({mode:'SCENARIO',record:scenario}):undefined],['SCENARIO RESULT',resultExists?scenario?.id:null,scenario?()=>setDrawer({mode:'SCENARIO',record:scenario}):undefined],['REMOTE OPERATION',op?.id,op?()=>openOperation(op.id):undefined],['STATION EVENT',stationEvent?`EVENT #${stationEvent.id}`:null,stationEvent?()=>openAudit({record_id:op.id,event_type:stationEvent.event_type,actor_id:stationEvent.actor_id,actor_role:stationEvent.actor_role,timestamp:stationEvent.timestamp,revision:stationEvent.station_revision,source:stationEvent.source}):undefined],['OBSERVATION',ob?.id,ob?()=>setDrawer({mode:'OBSERVATION',record:ob}):undefined],['REPORT',op?.latest_report?.id,op?.latest_report?()=>openOperation(op.id):undefined],['SYNC EVENT',sync?.event_id,sync?()=>setDrawer({mode:'SYNC',record:sync}):undefined],['HQ REVIEW',op?.outcome_review?.reviewed_at,op?.outcome_review?()=>openOperation(op.id):undefined],['RECONCILIATION',rec?.id,rec?()=>onNavigate('RECONCILIATION'):undefined]] as const;return <div className="cc-chain-nodes">{nodes.map(([label,id,action],i)=><div key={label}><button disabled={!id} onClick={action}><small>{label}</small><b>{id||'NOT AVAILABLE'}</b></button>{i<nodes.length-1&&<i>↓</i>}</div>)}</div>})()}</section>
      <section className="cc-panel cc-audit"><div className="cc-panel-head"><div><span className="cc-kicker">IMMUTABLE HISTORY</span><h2>RECENT AUDIT ACTIVITY</h2></div><button onClick={()=>setDrawer({mode:'AUDIT_LIST',records:data?.audit||[]})}>VIEW ALL <ArrowRight size={13}/></button></div>{data?.audit.length?data.audit.slice(0,5).map((e,i)=><button className="cc-audit-row" key={`${e.record_id}-${e.timestamp}-${i}`} onClick={()=>void openAudit(e)}><time>{date(e.timestamp)}</time><b>{e.event_type}</b><small>{e.actor_id} · {e.actor_role} · REV {e.revision} · {e.source}</small></button>):<p className="cc-empty">No audit events recorded yet.</p>}</section></div>
    <p className="cc-footnote">READ-ONLY OVERVIEW · all counts and records come from station-scoped persisted backend data. Browser-local offline events are not visible to HQ until synchronization.</p>
    {busy&&<span className="cc-refreshing">Refreshing from backend…</span>}
    {drawer&&<div className="cc-drawer-backdrop" onMouseDown={e=>e.target===e.currentTarget&&setDrawer(null)}><aside className="cc-drawer"><header><div><span className="cc-kicker">{drawer.mode==='PROVENANCE'?'DATA PROVENANCE':'RECORD EVIDENCE'}</span><h2>{drawer.title||drawer.record?.id||drawer.mode}</h2></div><button onClick={()=>setDrawer(null)} aria-label="Close"><X size={18}/></button></header>{drawer.mode==='PROVENANCE'?<><h3>{val(drawer.value)}</h3><dl>{Object.entries(drawer.meta||{}).map(([k,v])=><div key={k}><dt>{k.replaceAll('_',' ').toUpperCase()}</dt><dd>{typeof v==='object'?JSON.stringify(v):val(v)}</dd></div>)}</dl></>:drawer.mode==='AUDIT'||drawer.mode==='AUDIT_LIST'?<AuditContent value={drawer.record||drawer.records}/>:<pre className="cc-record-json">{JSON.stringify(drawer.record||drawer.records,null,2)}</pre>}<footer>Historical audit events are read-only.</footer></aside></div>}
  </main>
}

function AuditContent({value}:{value:any}){const rows=Array.isArray(value)?value:(value?.timeline||[]);const record=Array.isArray(value)?null:value;return <><dl>{(record?[['RECORD ID',record.id],['RECORD TYPE',record.operation_type||record.record_type],['STATION',record.station_id],['CREATED BY',record.created_by],['ROLE',record.created_by_role],['CREATED AT',record.created_at],['UPDATED AT',record.updated_at],['BASE REVISION',record.base_revision],['CURRENT REVISION',record.timeline?.at(-1)?.station_revision],['SOURCE',record.provenance?.source_type||record.timeline?.[0]?.source],['SCENARIO',record.scenario_id],['RELATED OBSERVATIONS',record.station_observations?.map((x:any)=>x.id).join(', ')]]:[]).map(([k,v])=><div key={String(k)}><dt>{k}</dt><dd>{val(v)}</dd></div>)}</dl><h3>EVENT TIMELINE · IMMUTABLE</h3><ol className="cc-audit-timeline">{rows.map((x:any,i:number)=><li key={`${x.timestamp||x.occurred_at}-${i}`}><b>{x.event_type}</b><time>{date(x.timestamp||x.occurred_at)}</time><small>{x.actor_id} · {x.actor_role} · REV {x.station_revision||x.revision} · {x.source||'HQ_REVIEW'}</small></li>)}</ol></>}
