import { useCallback, useEffect, useState } from 'react'
import { ArrowLeft, CloudOff, RefreshCw, Send } from 'lucide-react'

const EDGE = import.meta.env.VITE_EDGE_API_URL || 'http://127.0.0.1:8001'
const EDGE_TOKEN = import.meta.env.VITE_EDGE_TOKEN || 'local-edge-token'
type Props = { station:{id:string;code:string;name:string}; onBack:()=>void }

export function EdgeStationWorkspace({station,onBack}:Props){
 const [operations,setOperations]=useState<any[]>([]),[state,setState]=useState<any[]>([]),[outbox,setOutbox]=useState<any[]>([]),[selected,setSelected]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[observation,setObservation]=useState({metric:'CHP Availability',value:'Unavailable',unit:'state',observation_time:new Date().toISOString(),method:'Manual inspection',quality:'UNASSESSED',notes:''})
 const headers={Authorization:`Bearer ${EDGE_TOKEN}`,'Content-Type':'application/json'}
 const request=useCallback(async(path:string,init?:RequestInit)=>{const response=await fetch(`${EDGE}${path}`,{...init,headers:{...headers,...(init?.headers||{})}});const data=await response.json();if(!response.ok)throw new Error(data.detail||'Station edge request failed');return data},[station.id])
 const load=useCallback(async()=>{setError('');try{const [ops,stateDoc,queue]=await Promise.all([request(`/api/edge/operations?station_id=${station.id}`),request(`/api/edge/state?station_id=${station.id}`),request(`/api/edge/outbox?station_id=${station.id}`)]);setOperations(ops.operations);setState(stateDoc.values);setOutbox(queue.events);if(!selected&&ops.operations.length)setSelected(ops.operations[0].operation_id)}catch(e){setError(e instanceof Error?e.message:'Edge service unavailable')}},[request,station.id,selected])
 useEffect(()=>{void load()},[load])
 const active=operations.find(item=>item.operation_id===selected)
 async function sync(){setBusy(true);setError('');setNotice('');try{const result=await request('/api/edge/sync',{method:'POST',body:JSON.stringify({station_id:station.id})});setNotice(`SYNC COMPLETE · ${result.received_operation_ids.length} HQ request(s) delivered · ${result.sent.accepted.length+result.sent.already_applied.length} station event(s) received`);await load()}catch(e){setError(e instanceof Error?e.message:'Transport unavailable · local edge records retained')}finally{setBusy(false)}}
 async function action(name:string,payload:Record<string,unknown>={}){if(!active)return;setBusy(true);setError('');setNotice('');try{const result=await request(`/api/edge/operations/${encodeURIComponent(active.operation_id)}/${name}?station_id=${station.id}`,{method:'POST',body:JSON.stringify(payload)});setNotice(`${result.operation_id} · ${result.status} · STORED ON STATION EDGE · PENDING SYNC`);await load()}catch(e){setError(e instanceof Error?e.message:'Local station action failed')}finally{setBusy(false)}}
 async function saveObservation(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{const result=await request(`/api/edge/observations?station_id=${station.id}`,{method:'POST',body:JSON.stringify({...observation,operation_id:active?.operation_id||null})});setNotice(`${result.id} · MANUAL · PERSISTED ON EDGE · PENDING SYNC`);await load()}catch(e){setError(e instanceof Error?e.message:'Observation could not be saved locally')}finally{setBusy(false)}}
 const sample=(field:string)=>state.find(item=>item.field===field)
 return <main className="station-shell edge-workspace"><header className="station-head"><div><span className="header-kicker">INDEPENDENT STATION EDGE · {station.code}</span><h1>{station.name.replace(' Station','').toUpperCase()} · LOCAL OPERATIONS</h1><p>Station data and events are stored in the edge SQLite database, independently of HQ.</p></div><button className="station-secondary" onClick={onBack}><ArrowLeft size={15}/> RETURN TO STATION WORKSPACE</button></header>
  <div className="edge-status-strip"><span><small>EDGE AUTHORITY</small><b>LOCAL STORE</b></span><span><small>TRANSPORT</small><b>{outbox.length?'PENDING OUTBOX':'READY'}</b></span><span><small>UNSENT EVENTS</small><b>{outbox.filter(x=>x.sync_status!=='SYNCED').length}</b></span><button className="station-primary" onClick={()=>void sync()} disabled={busy}><RefreshCw size={15}/> FORCE SYNC THROUGH HQ GATEWAY</button></div>
  {error&&<div className="rom-alert" role="alert"><CloudOff size={16}/>{error}</div>}{notice&&<div className="rom-notice" role="status">{notice}</div>}
  <section className="edge-local-state"><div><span className="header-kicker">EDGE-OWNED STATE · DEMO SYNTHETIC</span><h2>Latest emulator state</h2></div><div className="edge-state-grid">{[['POWER','power_available'],['FUEL','fuel_reserve'],['THERMAL STATE','heat_indoor'],['WATER','water_reserve'],['CHP STATUS','chp_availability']].map(([label,key])=>{const item=sample(key);return <article key={key}><small>{label}</small><b>{item?`${item.value} ${item.unit}`:'UNKNOWN'}</b><em>{item?.source_type||'UNKNOWN'}</em></article>})}</div></section>
  <div className="edge-task-layout"><section className="edge-operation-list"><div className="scenario-section-head"><div><span className="header-kicker">HQ REQUESTS ALREADY RECEIVED BY EDGE</span><h2>Station inbox</h2></div><button className="station-icon" aria-label="Refresh edge inbox" onClick={()=>void load()}><RefreshCw size={15}/></button></div>{operations.map(item=><button className={`edge-operation ${selected===item.operation_id?'active':''}`} key={item.operation_id} onClick={()=>setSelected(item.operation_id)}><b>{item.envelope.title}</b><span>{item.operation_id} · {item.envelope.priority} · {item.status}</span><small>{item.envelope.scenario_id||'No linked scenario'} · base REV {item.envelope.base_revision}</small></button>)}{!operations.length&&<p className="scenario-empty">No HQ request is present locally. Restore the link and sync to receive queued HQ operations.</p>}</section>
   <section className="edge-task-detail"><span className="header-kicker">LOCAL HUMAN WORK · NO EQUIPMENT COMMANDS</span>{active?<><h2>{active.envelope.title}</h2><p>{active.envelope.description||'No additional request description.'}</p><div className="edge-task-meta"><span>STATUS <b>{active.status}</b></span><span>TYPE <b>{active.envelope.operation_type}</b></span></div><div className="edge-action-row">{active.status==='DELIVERED'&&<><button disabled={busy} onClick={()=>void action('seen')}>MARK SEEN</button><button disabled={busy} onClick={()=>void action('accept',{note:'Accepted locally by station operator.'})}>ACCEPT</button><button disabled={busy} onClick={()=>void action('decline',{note:'Declined locally by station operator.'})}>DECLINE</button></>}{active.status==='ACCEPTED'&&<button disabled={busy} onClick={()=>void action('progress',{note:'Station work started locally.'})}>START WORK</button>}{active.status==='IN_PROGRESS'&&<button disabled={busy} onClick={()=>void action('report-complete',{note:'Station work reported complete locally.'})}>REPORT COMPLETE</button>}</div><form className="edge-observation-form" onSubmit={saveObservation}><h3>Record manual observation</h3><label>Metric<input value={observation.metric} onChange={e=>setObservation({...observation,metric:e.target.value})} required/></label><label>Value<input value={observation.value} onChange={e=>setObservation({...observation,value:e.target.value})} required/></label><label>Unit<input value={observation.unit} onChange={e=>setObservation({...observation,unit:e.target.value})} required/></label><label>Observation time<input type="datetime-local" value={observation.observation_time.slice(0,16)} onChange={e=>setObservation({...observation,observation_time:new Date(e.target.value).toISOString()})} required/></label><label>Method<input value={observation.method} onChange={e=>setObservation({...observation,method:e.target.value})} required/></label><label>Quality<select value={observation.quality} onChange={e=>setObservation({...observation,quality:e.target.value})}><option>UNASSESSED</option><option>GOOD</option><option>BAD</option></select></label><button className="station-primary" disabled={busy||!active}><Send size={14}/> SAVE TO LOCAL EDGE OUTBOX</button></form></>:<p className="scenario-empty">Select an operation to inspect its local state and record station work.</p>}</section></div>
  <section className="edge-outbox"><div className="scenario-section-head"><div><span className="header-kicker">DURABLE EDGE JOURNAL</span><h2>Station outbox</h2></div><b>{outbox.filter(x=>x.sync_status!=='SYNCED').length} PENDING</b></div>{outbox.map(item=><div className="edge-outbox-item" key={item.event_id}><b>{item.event_type.toUpperCase()}</b><span>{item.operation_id}</span><code>{item.event_id}</code><small>{item.sync_status} · local REV {item.local_revision}</small></div>)}{!outbox.length&&<p className="scenario-empty">No unsent station events.</p>}</section>
 </main>
}
