import { useEffect, useState } from 'react'
import { ArrowLeft, ArrowRight, RefreshCw, ShieldCheck } from 'lucide-react'

const API=import.meta.env.VITE_API_URL||'http://127.0.0.1:8000'
type Case={id:string;station_id:string;scenario_id:string|null;operation_id:string;created_at:string;status:string;projection_snapshot:any;observation_snapshot:any;comparison_result:any;review_classification:string|null;review_notes:string;model_version:string|null;current_revision:number;reviewed_by?:string|null;reviewed_at?:string|null;events:any[];operation_title?:string;operation_status?:string;scenario_name?:string;last_updated?:string;follow_up_operation_id?:string|null}
type Props={token:string;station:{id:string;name:string;code:string}}
const human=(s:string)=>s.replaceAll('_',' ')
export function Reconciliation({token,station}:Props){
 const [cases,setCases]=useState<Case[]>([]),[operations,setOperations]=useState<any[]>([]),[selected,setSelected]=useState<Case|null>(null),[provenance,setProvenance]=useState<any>(null),[status,setStatus]=useState('ALL'),[classification,setClassification]=useState(''),[notes,setNotes]=useState(''),[follow,setFollow]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState(''),[message,setMessage]=useState('')
 const headers={Authorization:`Bearer ${token}`,'Content-Type':'application/json'}
 async function load(){setError('');try{const [a,b]=await Promise.all([fetch(`${API}/api/reconciliation`,{headers:{Authorization:`Bearer ${token}`}}),fetch(`${API}/api/operations`,{headers:{Authorization:`Bearer ${token}`}})]);for(const r of [a,b])if(!r.ok)throw new Error((await r.json()).detail||'Reconciliation data unavailable');const rd=await a.json(),od=await b.json();setCases(rd.reconciliations);setOperations(od.operations.filter((x:any)=>['REPORTED_COMPLETE','REPORTED_BLOCKED','REVIEWED_OUTCOME','CLOSED','REOPENED'].includes(x.status)));if(selected){const fresh=rd.reconciliations.find((x:Case)=>x.id===selected.id);if(fresh)setSelected(fresh)}else if(rd.reconciliations.length){const initial=rd.reconciliations.find((x:Case)=>x.status==='NOT_REVIEWED'||x.status==='REOPENED')||rd.reconciliations[0];await openCase(initial)}}catch(e){setError(e instanceof Error?e.message:'Reconciliation data unavailable')}}
 useEffect(()=>{void load()},[token,station.id])
 async function request(path:string,body?:unknown){const r=await fetch(`${API}${path}`,{method:body?'POST':'GET',headers,body:body?JSON.stringify(body):undefined});const d=await r.json();if(!r.ok)throw new Error(d.detail||'Request failed');return d}
 async function openCase(item:Case){setSelected(item);setError('');try{const p=await request(`/api/reconciliation/${item.id}/provenance`);setProvenance(p);setClassification(item.review_classification||'');setNotes(item.review_notes||'')}catch(e){setError(e instanceof Error?e.message:'Provenance unavailable')}}
 async function create(op:any){setBusy(true);setError('');try{const c=await request(`/api/reconciliation/${op.id}/create`,{});await load();await openCase(c);setMessage('Projection check created from stored scenario and station report snapshots.')}catch(e){setError(e instanceof Error?e.message:'Could not create projection check')}finally{setBusy(false)}}
 async function review(e:React.FormEvent){e.preventDefault();if(!selected)return;setBusy(true);setError('');try{const d=await request(`/api/reconciliation/${selected.id}/review`,{classification,notes,follow_up_action:follow});setSelected(d);await load();setMessage('HQ review recorded in the reconciliation and operation audit trails.')}catch(e){setError(e instanceof Error?e.message:'Review was not saved')}finally{setBusy(false)}}
 async function reopen(){if(!selected)return;setBusy(true);try{const d=await request(`/api/reconciliation/${selected.id}/reopen`,{note:'Reopened by HQ for new evidence review'});setSelected(d);setClassification('');setNotes('');await load();setMessage('Reconciliation reopened. Earlier review remains in the immutable event history.')}catch(e){setError(e instanceof Error?e.message:'Could not reopen')}finally{setBusy(false)}}
 async function createFollowUp(){if(!selected)return;const reviewEvent=[...selected.events].reverse().find((e:any)=>e.event_type==='RECONCILIATION_REVIEWED'),requested=reviewEvent?.payload?.follow_up_action;if(!requested){setError('Add a follow-up action in the review notes before creating a request.');return}setBusy(true);try{const r=await fetch(`${API}/api/reconciliation/${selected.id}/follow-up`,{method:'POST',headers:{...headers,'Idempotency-Key':crypto.randomUUID()},body:JSON.stringify({operation_type:'SCENARIO_FOLLOWUP',title:`Follow up · ${selected.operation_id}`,description:requested,priority:'P2'})}),d=await r.json();if(!r.ok)throw new Error(d.detail||'Follow-up could not be created');setMessage(`Follow-up ${d.id} created at current REV ${d.base_revision}.`);await load()}catch(e){setError(e instanceof Error?e.message:'Follow-up could not be created')}finally{setBusy(false)}}
 const existing=new Set(cases.map(x=>x.operation_id)),ready=operations.filter(x=>!existing.has(x.id)),shown=cases.filter(x=>status==='ALL'||x.status===status)
 const scenario=selected?.projection_snapshot,report=selected?.observation_snapshot
 return <section className="recon-shell"><header className="recon-header"><div><span className="header-kicker">HQ · EVIDENCE REVIEW · HUMAN CLASSIFICATION</span><h1>RECONCILIATION</h1><p>{station.name} · Compare stored scenario projections with station-reported outcomes.</p></div><button className="station-icon" onClick={()=>void load()} aria-label="Refresh reconciliation"><RefreshCw size={16}/></button></header>
 {error&&<div className="rom-alert" role="alert">{error}</div>}{message&&<div className="rom-notice" role="status">{message}</div>}
 <div className="recon-columns"><aside className="recon-register"><div className="station-list-top"><div><span className="header-kicker">REVIEW REGISTER</span><h2>{cases.length.toString().padStart(2,'0')} CASES</h2></div><ShieldCheck size={18}/></div><label className="rom-filter">Show<select value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All cases</option><option value="NOT_REVIEWED">Pending review</option><option value="REVIEWED">Reviewed</option><option value="REOPENED">Reopened</option></select></label>{shown.map(x=><button key={x.id} className={`station-request ${selected?.id===x.id?'active':''}`} onClick={()=>void openCase(x)}><span className="station-request-type">{station.code}<i>{human(x.status)}</i></span><strong>{x.scenario_name||x.scenario_id||'No linked scenario'}</strong><small>{x.operation_title} · {x.operation_id}</small><small>Station report: {human(x.observation_snapshot?.operation_status||'')}</small><small>Projection comparison: {x.comparison_result.status}</small></button>)}{!shown.length&&<p className="station-empty">No reconciliation cases in this group.</p>}</aside>
 <main className="recon-main">{selected?<><div className="recon-case-head"><div><span className="header-kicker">{selected.id} · {selected.operation_id}</span><h2>{selected.scenario_name||scenario?.name||selected.scenario_id||'Station outcome without scenario'}</h2><p>{selected.status==='NOT_REVIEWED'?'Awaiting explicit HQ review':human(selected.status)} · model {selected.model_version||'UNKNOWN'} · current REV {selected.current_revision}</p></div><span className={`rom-status status-${selected.status.toLowerCase()}`}>{human(selected.status)}</span></div>
 <div className="recon-evidence-grid"><article><span className="header-kicker">SCENARIO PROJECTION · STORED SNAPSHOT</span>{scenario?<><h3>{scenario.name}</h3><p>Scenario {scenario.id} · {new Date(scenario.created_at).toLocaleString()}</p><p>Base REV {scenario.base_revision} · MODEL {scenario.model_version}</p><h4>Projected outputs</h4><dl>{Object.entries(scenario.result?.projected||{}).map(([k,v])=><div key={k}><dt>{human(k)}</dt><dd>{String(v??'UNKNOWN')}</dd></div>)}</dl><h4>Inputs / assumptions</h4><pre>{JSON.stringify(scenario.inputs,null,2)}</pre><h4>Constraints and uncertainty</h4><pre>{JSON.stringify({constraints:scenario.result?.constraints,uncertainties:scenario.result?.uncertainties,assumptions:scenario.result?.assumptions},null,2)}</pre><b className="manual-badge">SCENARIO ASSUMPTION · MODEL OUTPUT</b></>:<p>NOT COMPARABLE · This operation has no linked scenario snapshot.</p>}</article>
 <article><span className="header-kicker">STATION REPORT · STATION-REPORTED</span><h3>{human(report?.operation_status||'No report')}</h3>{report?.report&&<><p>{report.report.reported_by} · {report.report.reported_role} · {new Date(report.report.reported_at).toLocaleString()}</p><pre>{JSON.stringify(JSON.parse(report.report.observations_json||'{}'),null,2)}</pre></>}{report?.observations?.map((o:any)=><div className="recon-observation" key={o.id}><b>{o.metric}: {o.value} {o.unit}</b><span>{o.observation_time} · {o.method} · {o.source_type} · REV {o.station_revision}</span><p>{o.notes}</p></div>)}{report?.evidence?.map((e:any)=><p key={e.id}>Evidence · {e.label} · {e.source_type}</p>)}<b className="manual-badge">NOT INDEPENDENTLY VERIFIED</b></article>
 <article><span className="header-kicker">PROJECTION CHECK · EVIDENCE COMPARISON</span><p className="comparison-status">{human(selected.comparison_result.status)}</p>{selected.comparison_result.items?.map((item:any,i:number)=><div className="comparison-item" key={`${item.metric}-${i}`}><b>{item.metric} · {human(item.type)}</b>{item.type==='DIRECT_COMPARISON'?<><div>Projected <strong>{item.projected_value} {item.unit}</strong></div><div>Station reported <strong>{item.observed_value} {item.unit}</strong></div><div>Absolute difference <strong>{item.absolute_difference} {item.unit}</strong></div><div>Relative difference <strong>{item.relative_difference_pct===null?'Not meaningful':`${item.relative_difference_pct.toFixed(2)}%`}</strong></div></>:<><div>Scenario assumption <strong>{item.scenario_assumption}</strong></div><div>Station reported <strong>{item.station_reported}</strong></div></>}<small>{item.provenance||'Stored scenario snapshot / station report'} · comparison only, no automatic verdict</small></div>)}{!selected.comparison_result.items?.length&&<p>NOT COMPARABLE · {selected.comparison_result.reason}</p>}</article></div>
 <section className="provenance-chain"><span className="header-kicker">PROVENANCE CHAIN</span><div>{(provenance?.chain||[]).map((item:any,i:number)=><span key={`${item.type}-${i}`}><b>{item.type}</b><small>{item.id||item.items?.length+' events'||'—'}</small>{i<(provenance.chain.length-1)&&<ArrowRight size={14}/>}</span>)}</div></section>
 {selected.status==='REVIEWED'&&<div className="rom-notice">HQ REVIEW · {selected.review_classification} · {selected.reviewed_by} · {selected.reviewed_at}<p>{selected.review_notes}</p>{selected.events.some((e:any)=>e.payload?.follow_up_action)&&<button onClick={()=>void createFollowUp()} disabled={busy}>{selected.follow_up_operation_id?`FOLLOW-UP ${selected.follow_up_operation_id}`:'CREATE FOLLOW-UP REQUEST'}</button>}<button onClick={()=>void reopen()} disabled={busy}>REOPEN RECONCILIATION</button></div>}
 {selected.status!=='REVIEWED'&&<form className="recon-review" onSubmit={review}><span className="header-kicker">HQ ANALYST REVIEW · EXPLICIT CLASSIFICATION REQUIRED</span><label>Review outcome<select required value={classification} onChange={e=>setClassification(e.target.value)}><option value="">Choose assessment</option><option value="CONSISTENT_WITH_PROJECTION">Consistent with projection</option><option value="PARTIALLY_CONSISTENT">Partially consistent</option><option value="DIFFERS_FROM_PROJECTION">Differs from projection</option><option value="INSUFFICIENT_EVIDENCE">Insufficient evidence</option><option value="NOT_COMPARABLE">Not comparable</option></select></label><label>Review notes<textarea required value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Describe how the stored projection and station report relate."/></label><label>Optional follow-up action<input value={follow} onChange={e=>setFollow(e.target.value)} placeholder="e.g. Request a repeat temperature measurement"/></label><button className="station-submit" disabled={busy||!classification}>{busy?'Saving review…':'SAVE HQ REVIEW'}</button></form>}
 <section className="station-timeline"><span className="header-kicker">RECONCILIATION AUDIT · IMMUTABLE EVENTS</span><ol>{selected.events.map((ev:any)=><li key={ev.id}><b>{human(ev.event_type)}</b><small>{ev.actor_id} · {ev.actor_role} · {new Date(ev.occurred_at).toLocaleString()}</small><details><summary>View immutable event snapshot</summary><pre>{JSON.stringify(ev.payload,null,2)}</pre></details></li>)}</ol></section></>:<div className="recon-empty"><span className="header-kicker">WHAT HAPPENED AFTER HQ ISSUED THE REQUEST?</span><h2>Select a reviewed case or create a Projection Check.</h2></div>}</main></div>
 {ready.length>0&&<section className="recon-ready"><span className="header-kicker">STATION OUTCOMES READY FOR PROJECTION CHECK</span>{ready.map(op=><article key={op.id}><div><b>{op.title}</b><span>{op.id} · {human(op.status)} · scenario {op.scenario_id||'none'}</span></div><button disabled={busy} onClick={()=>void create(op)}>CREATE PROJECTION CHECK <ArrowRight size={14}/></button></article>)}</section>}
 </section>
}
