import { Info } from 'lucide-react'

type Props={state:any[];revision:number|null|undefined;onSource:(field:string,value:string,metadata:any)=>void;large?:boolean;onViewModel?:()=>void}
export function TwinSnapshot({state,revision,onSource,large=false,onViewModel}:Props){
 const values=Object.fromEntries((state||[]).map(x=>[x.field,x]))
 const show=(field:string)=>{const x=values[field];onSource(x?.field||field,`${x?.value??'—'} ${x?.unit||''}`.trim(),{source:x?.source_type,source_type:x?.source_type,observation_time:x?.observed_at,station_revision:x?.revision,model_version:x?.model_version,quality:x?.quality})}
 const format=(value:any)=>typeof value==='number'&&Number.isFinite(value)?new Intl.NumberFormat('en-IN',{maximumFractionDigits:2}).format(value):typeof value==='string'&&value.trim()&&Number.isFinite(Number(value))?new Intl.NumberFormat('en-IN',{maximumFractionDigits:2}).format(Number(value)):value??'—'
 const metric=(field:string)=>{const x=values[field];return `${format(x?.value)}${x?.unit?` ${x.unit}`:''}`}
 return <section className={`cc-panel cc-twin ${large?'cc-twin-large':''}`}><div className="cc-panel-head"><div><span className="cc-kicker">CURRENT DEPENDENCY MODEL · REV #{revision??'—'}</span><h2>DIGITAL TWIN</h2><p className="cc-twin-subtitle">Station state · source-labelled operational snapshot</p></div><button onClick={onViewModel||(()=>show('power_available'))}>{onViewModel?'VIEW 3D DIGITAL TWIN':'VIEW SOURCE'} <Info size={13}/></button></div><div className="cc-engineering-flow"><button className="cc-node cc-source" onClick={()=>show('fuel_reserve')}><small>INPUT</small><b>FUEL</b><span>{metric('fuel_reserve')}</span></button><i className="cc-connector">→</i><div className="cc-engine"><button className="cc-node cc-chp" onClick={()=>show('chp_available')}><svg className="cc-chp-glyph" viewBox="0 0 52 38" aria-hidden="true"><path d="M5 13h28v20H5zM9 8V3h6v5m13 0V3h5v5"/><circle cx="16" cy="23" r="5"/><path d="M33 17h8v12h-8M41 20h6m-6 6h6M11 13l2 4m5-4 2 4"/><path d="m39 3-4 7h5l-3 6 8-9h-5l3-4"/></svg><span className="cc-chp-copy"><small>COMBINED HEAT &amp; POWER</small><b>CHP</b><span>STATUS · {metric('chp_available')}</span></span></button><div className="cc-output-branch"><div className="cc-branch-lines" aria-hidden="true"><i/><i/></div><div className="cc-output-nodes"><button className="cc-node" onClick={()=>show('power_available')}><small>STATION POWER</small><b>{metric('power_available')}</b></button><button className="cc-node" onClick={()=>show('heat_indoor')}><small>INDOOR TEMPERATURE</small><b>{metric('heat_indoor')}</b></button></div></div><i className="cc-connector cc-down">↓</i><button className="cc-node cc-water" onClick={()=>show('water_production')}><small>WATER PRODUCTION</small><b>{metric('water_production')}</b></button><i className="cc-connector cc-down">↓</i><button className="cc-node cc-water" onClick={()=>show('water_reserve')}><small>WATER STORAGE</small><b>{metric('water_reserve')}</b></button></div><div className="cc-load-column"><span className="cc-load-link">← DISTRIBUTION</span><button className="cc-node" onClick={()=>show('critical_load')}><small>CRITICAL LOAD</small><b>{metric('critical_load')}</b></button><button className="cc-node" onClick={()=>show('deferrable_load')}><small>DEFERRABLE LOAD</small><b>{metric('deferrable_load')}</b></button></div></div><div className="cc-twin-legend"><span><small>STATE SOURCE</small><b>{state?.length?String(state[0]?.source_type||'DEMO SYNTHETIC / MANUAL'):'NO RECORDED STATE'}</b></span><span><small>MODEL STATUS</small><b>PROTOTYPE · READ ONLY</b></span><span><small>PROVENANCE</small><b>SELECT A VALUE TO INSPECT</b></span></div><p className="cc-caveat">Operational values remain distinct from environmental observations and projected scenario results. This model does not control equipment.</p></section>
}
